use mavenmovies;

##Question 1:
/*Retrieve the total number of rentals made in the Sakila database.
Hint: Use the COUNT() function.*/

select count(rental_id)as total_rental from rental ;
select *from rental;

##Question 2:
/*Find the average rental duration (in days) of movies rented from the Sakila database.
Hint: Utilize the AVG() function.
Also ensures that only completed rentals should be considered in the average calculation.*/

select avg(datediff(return_date ,rental_date))as rental_duration from rental; 

##Question 3:
/*Display the first name and last name of customers in uppercase.
Hint: Use the UPPER () function.*/

select upper(concat(first_name, ' ',last_name))as full_name from customer ;

##Question 4:
/*Extract the month from the rental date and display it along side the rental ID.
Hint: Employ the MONTH() function.*/

select rental_id,rental_date, month(return_date)as rental_month ,year(return_date)as rental_year,day(return_date)as rental_day from rental ;
select count(rental_id) from rental where year(rental_date)=2005 and month(rental_date)=8 and day(rental_date)=21;

/*
Query 1. Find the number of rentals that occur on a daily basis
Query 2. Find which day of the week has the most rentals*/

##1Query A. Find the number of rentals that occur on a daily basis

select * from rental;
select date_format(rental_date, "%y-%m-%d") as rental_date ,count(rental_id) from rental group by rental_date;
select date_format(rental_date,"%y-%m-%d")as Num_of_rental_days ,count(rental_id)as total_rental from rental group by Num_of_rental_days;

##Query B. Find which day of the week has the most rentals

select date_format(rental_date, "%W")as day_of_week ,count(rental_id) total_count from rental group by day_of_week;

##Question 5:
/*Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
Hint: Use COUNT () in conjunction with GROUP BY.*/

select 
count(r.rental_id)as total_rental
from customer c
inner join rental r on c.customer_id=r.customer_id
;

##Question 6:
/*Find the total revenue generated by each store.
Hint: Combine SUM() and GROUP BY.*/

select s.store_id ,sum(p.amount) 
from store s
inner join payment p on s.manager_staff_id=p.staff_id 
group by  s.store_id ; 
select * from store;

##Question 7:a
/*Display the title of the movie, customer s first name, and last name who rented it.
Hint: Use JOIN between the film, inventory, rental, and customer tables.
GROUP BY:*/

## execution: inventory ,film ,rental ,customer 

select * from film;
select * from inventory;
select * from rental;
select * from customer;

select 
f.title ,
concat(c.first_name," " ,c.last_name)as full_name 
from inventory i 
inner join film f on f.film_id=i.film_id
inner join rental r on r.inventory_id=i.inventory_id 
inner join customer c on c.customer_id=r.customer_id
order by full_name ;


##Question 8:
/* Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
Hint: Use JOIN between the film actor, film, and actor tables.*/

select *from film_actor;
select * from film;
select * from actor;

select  
a.first_name,
f.title
from film f 
join film_actor fa on f.film_id= fa.film_id
join actor a on a.actor_id= fa.actor_id
where f.title="ACE GOLDFINGER";


##Question 9:
/*Determine the total number of rentals for each category of movies.
Hint: JOIN film_category, film, and rental tables, then use cOUNT () and GROUP BY.*/

select * from film_category;
select * from film;
select * from rental;

SELECT 
fc.category_id, 
COUNT(rental_id) AS total_rentals
FROM film_category fc
JOIN film f ON fc.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY fc.category_id;

 
##Question 10:
/*Find the average rental rate of movies in each language.
Hint: JOIN film and language tables, then use AVG () and GROUP BY.*/

select * from language;
select * from rental;
select * from inventory;
select * from film;
desc language;
desc film;

select
l.name ,
avg(f.rental_rate)as avg_rental_rate
from 
language l 
inner join film f on l.language_id= f.language_id
Group by l.name ;

##Question 11:
/*Retrieve the customer names along with the total amount they have spent on rentals.
Hint: JOIN customer, payment, and rental tables, then use SUM() and GROUP BY.*/

select * from customer;
select * from rental;
select * from payment;

select 
c.customer_id,
concat(c.first_name," " ,c.last_name) as full_name,
sum(p.amount)as total_amount
from 
customer c 
inner join payment p on c.customer_id=p.customer_id
GROUP BY 
c.customer_id,
full_name  ;


##Question 12:
/*List the titles of movies rented by each customer in a particular city (e.g., 'London').*/

select * from customer;
select * from city;
select * from address;
select * from rental;
select * from inventory;
select * from film;

select 
f.title,
concat(c.first_name, " " ,c.last_name)as customer_name,
ct.city 
from customer c
inner join rental r on c.customer_id=r.customer_id
inner join inventory i on r.inventory_id= i.inventory_id
inner join film f on i.film_id= f.film_id
inner join address a on c.address_id= a.address_id
inner join city ct on a.city_id=ct.city_id
where city="london";

##Question 13:
/*Display the top 5 rented movies along with the number of times they have been rented.*/

select * from film;
select * from rental;
select * from inventory;
select * from payment;

SELECT 
f.title,
COUNT(*) AS total_rentals
FROM film f
JOIN film fc ON fc.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY 
f.title
ORDER BY 
total_rentals DESC LIMIT 5;

##version 1
select 
f.title,
count(r.rental_id)as total_rental_count
from film f
inner join inventory i on f.film_id=i.film_id
inner join rental r on i.inventory_id=r.inventory_id
inner join payment p on r.rental_id=p.rental_id
group by f.title
order by total_rental_count desc
 limit 5;

#version 2

select 
f.title,
count(p.rental_id)as total_rental_count
from film f
inner join inventory i on f.film_id=i.film_id
inner join rental r on i.inventory_id=r.inventory_id
inner join payment p on r.rental_id=p.rental_id
group by f.title
order by total_rental_count desc
 limit 5;

##Question 14:
/*Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).*/

select * from customer;
select * from rental;
select * from store;
select * from inventory ;
desc store;

##wrong answer
select 
c.customer_id,
count(distinct i.store_id) as total_store
from  customer c
inner join rental r on c.customer_id=r.customer_id
inner join inventory i on r.inventory_id=i.inventory_id
inner join store s on i.store_id=s.store_id
group by c.customer_id
having total_store=2;

##new
select 
c.customer_id,
count(distinct r.store_id)as total_no_stores
from store s
inner join customer c on s.store_id=c.store_id
inner join rental r on c.customer_id= r.customer_id
group by c.customer_id
having count(distinct s.store_id =2); 

with cte as (
 select 
c.customer_id,
count(distinct i.store_id) as total_store
from  customer c
inner join rental r on c.customer_id=r.customer_id
inner join inventory i on r.inventory_id=i.inventory_id
inner join store s on i.store_id=s.store_id
group by c.customer_id
having total_store=2
 )
select customer_id from cte ;
       
#************************************************************************************************************************8

##Question 1:
/*Retrieve the total number of rentals made in the Sakila database.
Hint: Use the COUNT() function.*/

##Question 2:
/*Find the average rental duration (in days) of movies rented from the Sakila database.
Hint: Utilize the AVG() function.
Also ensures that only completed rentals should be considered in the average calculation.*/

##Question 3:
/*Display the first name and last name of customers in uppercase.
Hint: Use the UPPER () function.*/

##Question 4:
/*Extract the month from the rental date and display it along side the rental ID.
Hint: Employ the MONTH() function.*/

##Question 5:
/*Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
Hint: Use COUNT () in conjunction with GROUP BY.*/

##Question 6:
/*Find the total revenue generated by each store.
Hint: Combine SUM() and GROUP BY.*/

##Question 7:a
/*Display the title of the movie, customer s first name, and last name who rented it.
Hint: Use JOIN between the film, inventory, rental, and customer tables.
GROUP BY:*/

##Question 8:
/* Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
Hint: Use JOIN between the film actor, film, and actor tables.*/

##Question 9:
/*Determine the total number of rentals for each category of movies.
Hint: JOIN film_category, film, and rental tables, then use cOUNT () and GROUP BY.*/
 
##Question 10:
/*Find the average rental rate of movies in each language.
Hint: JOIN film and language tables, then use AVG () and GROUP BY.*/

##Question 11:
/*Retrieve the customer names along with the total amount they have spent on rentals.
Hint: JOIN customer, payment, and rental tables, then use SUM() and GROUP BY.*/

##Question 12:
/*List the titles of movies rented by each customer in a particular city (e.g., 'London').
Hint: JOIN customer, address, city, rental, inventory, and film tables, then use GROUP BY.*/

##Question 13:
/*Display the top 5 rented movies along with the number of times they have been rented.
Hint: JOIN film, inventory, and rental tables, then use cOUNT() and GROUP BY, and limit the results*/

##Question 14:
/*Determine the customers who have rented movies from both stores (store ID 1 and store ID 2).
Hint: Use JOINS with rental, inventory, and customer tables and consider COUNT() and GROUP BY.*/

