##window in function

use mavenmovies;

## /*1. **Rank the customers based on the total amount they've spent on rentals.**/

select * from customer;
select * from rental;
select * from payment;

select subquery.customer_id,
rank() over (order by total_amount_spent desc)as customer_rank
from(
select c.customer_id,
c.first_name ,
sum(p.amount) as total_amount_spent
from customer c
join rental r on c.customer_id=r.customer_id
join payment p on r.rental_id=p.rental_id
group by c.customer_id
) as subquery;

with Amit as (
select c.customer_id,
c.first_name ,
sum(p.amount) as total_amount_spent 
from customer c
join rental r on c.customer_id=r.customer_id
join payment p on r.rental_id=p.rental_id
group by c.customer_id
)
select customer_id,
total_amount_spent ,
rank() over(order by  total_amount_spent desc) as customer_rank
from amit ;

/*2. **Calculate the cumulative revenue generated by each film over time.**/

select * from film;
select * from rental;
select * from payment;
select * from inventory;

select sum(p.amount)as total_revenue,
f.title 
from rental r
inner join payment p on r.rental_id=p.rental_id
inner join inventory i on r.inventory_id=i.inventory_id
inner join film f on i.film_id=f.film_id
group by f.title ;

with harsha as (
select sum(p.amount)as total_revenue,
f.title 
from rental r
inner join payment p on r.rental_id=p.rental_id
inner join inventory i on r.inventory_id=i.inventory_id
inner join film f on i.film_id=f.film_id
group by f.title
)
select 
title,
sum(total_revenue) ,
rank() over(order by title )as cumulative_revenue
from harsha;


/*3. **Determine the average rental duration for each film, considering films with similar lengths.**/

select * from film;
select * from rental;


4. **Identify the top 3 films in each category based on their rental counts.**


5. **Calculate the difference in rental counts between each customer's total rentals and the average rentals
across all customers.**


6. **Find the monthly revenue trend for the entire rental store over time.**


7. **Identify the customers whose total spending on rentals falls within the top 20% of all customers.**


8. **Calculate the running total of rentals per category, ordered by rental count.**


9. **Find the films that have been rented less than the average rental count for their respective categories.**


10. **Identify the top 5 months with the highest revenue and display the revenue generated in each month.**